forge "http://forge.puppetlabs.com"


mod "stdlib",
  :git => "git://github.com/puppetlabs/puppetlabs-stdlib.git",
  :ref => "master"

mod "apt",
  :git => "git://github.com/puppetlabs/puppetlabs-apt.git",
  :ref => "2.2.0"

mod "concat",
  :git => "git://github.com/puppetlabs/puppetlabs-concat.git",
  :ref => "2.0.1"

mod "jenkins",
  :git => "git://github.com/jenkinsci/puppet-jenkins.git",
  :ref => "v1.5.0"

mod "mysql",
  :git => "git://github.com/puppetlabs/puppetlabs-mysql.git",
  :ref => "master"

mod "postgresql",
  :git => "https://github.com/puppetlabs/puppetlabs-postgresql",
  :ref => "master"

mod "nginx",
  :git => "https://github.com/jfryman/puppet-nginx.git",
  :ref => "v0.2.7"

mod "apache",
  :git => "git://github.com/puppetlabs/puppetlabs-apache.git",
  :ref => "1.6.0"

mod "puppetdb",
  :git => "git://github.com/puppetlabs/puppetlabs-puppetdb.git",
  :ref => "5.0.0"

mod "puppetdbquery",
  :git => "git://github.com/dalen/puppet-puppetdbquery.git",
  :ref => "1.6.1"

mod "php",
  :git => "https://github.com/thias/puppet-php.git",
  :ref => "1.1.1"

mod "vcsrepo",
  :git => "https://github.com/puppetlabs/puppetlabs-vcsrepo.git",
  :ref => "1.3.1"

mod "composer",
  :git => "https://github.com/willdurand/puppet-composer.git",
  :ref => "v1.1.1"
