forge "http://forge.puppetlabs.com"


mod "stdlib",
  :git => "git://github.com/puppetlabs/puppetlabs-stdlib.git",
  :ref => "v2.2.1"

mod "apt",
  :git => "git://github.com/puppetlabs/puppetlabs-apt.git",
  :ref => "1.2.0"

mod "jenkins",
  :git => "git://github.com/jenkinsci/puppet-jenkins.git",
  :ref => "release-0.2.4"
