#!/bin/sh

VMWARE_TOOLS='false'


for x in $(cat /proc/cmdline); do
  case $x in
    VMWARE_TOOLS)
      VMWARE_TOOLS='true'
    ;;
  esac
done

echo 'bla bla' . $VMWARE_TOOLS

/bin/bash /sbin/do-debian-installation
