#!/bin/sh
#
### BEGIN INIT INFO
# Provides:          livecd-system
# Required-Start:    $all
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Wrapper to execute specific scripts during boot
# Description:       This is just a wrapper to execute some scripts during boot
#                    and shutdown of the system
### END INIT INFO

NAME="livecd-system"

. /lib/lsb/init-functions

do_start()
{
  echo ""
  boot-actions
  return 0
}

do_stop()
{
  echo ""
  shutdown-actions
  return 0
}


case "$1" in
  start|restart)
    log_begin_msg "Starting $NAME..."
    do_start
    log_end_msg $?
  ;;

  reload|force-reload|force-stop|status)
    echo "Error: argument '$1' not supported" >&2
    exit 3
  ;;

  stop)
    log_begin_msg "Stopping $NAME..."
    do_stop
    log_end_msg $?
  ;;

  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart}"
    exit 3
  ;;
esac

exit 0
